### ISSUE TITLE
i2c

### ISSUE THREAD

**Issue by antimodular** [PulsedLight3D/LIDARLite_v2_Arduino_Library#1]
hi
we have 40 of your new v2 sensor. 
do you have example code to get 2 sensors via i2c working on the same arudino.
using our old code from v1 did not produce results.
thanks.

**Comment by antimodular** [comment]
your support team suggests to use the changeI2cAddress  example but the .cpp file does not have a corresponding function.
so arduino prints this error:
test_lidarv2_2.ino:34:18: error: 'class LIDARLite' has no member named 'changeI2cAddress'

**Comment by rbscharette** [comment]
There seem to be the following function in the library: changeAddress
You can see it here:
LIDARLite.cpp:489-558
LIDARLite.h:17

**Comment by ak5a** [comment]
The "change i2c address" functions will be undergoing some tweaks (new functions for multi-sensor, etc). In the next few days. This is a new feature in the sensor and I'm playing with a lot of different ways of approaching it. So sorry if this changes anything in your code down the line. If I change or replace a function I'll be sure to put it in the update notes.
