### ISSUE TITLE
changeAddressMultisensor not a function in .cpp

### ISSUE THREAD

**Issue by antimodular** [PulsedLight3D/LIDARLite_v2_Arduino_Library#2]
FYI the arduino example sketch uses changeAddressMultisensor but the .cpp file only has changeAddressMultiPwrEn function. 
Once replaced the sketch works fine.

I changed it to only read 2 sensors.

Here some reading examples. you can see once in a while the reading jumps to 1061
https://gist.github.com/antimodular/0458a27eaf9db95dd9ad
https://gist.github.com/antimodular/b901c92ad182b63fb1eb

**Comment by ak5a** [comment]
Great catch! Thanks so much. I've updated and committed the change. 

Regarding the jumping, thanks for sharing that too... we think that's a power issue from the Arduino... while the capacitor helps it can also cause its own issues. We're looking into a power-regulator to add to the setup which should help. I'll post that as soon as we figure it out!
