### ISSUE TITLE
LIDARLite v2 initialization 

### ISSUE THREAD

**Issue by nchandol** [PulsedLight3D/LIDARLite_v2_Arduino_Library#3]
Hi,

I have connected two LIDAR-Lite version 2 sensors to an Arduino mini 5V, 16MHz as demonstrated in the notes of the library. I have modified the Change_I2C_Addresses.ino code two read from both my sensors. 

When loading the code into the arduino, it doesn't work unless I heat the reset button at the arduino. After that, I am getting the distance readings correctly. This problem continues every time I disconnect the power on my arduino. When I connect the power cable again, in order for the sensors to properly  work I need to hit the reset button again.

After searching online and experimenting a little bit with the code, I found out that if in the setup function I delay the initialization of the LIDARLite library it is working fine and I don't have to hit reset every time. Is this a known issue?

Than you in advance for you time! :)

You can find the code here (please note that 'beep()' is an external function):

```
/* =============================================================================
  LIDAR-Lite v2: Change the I2C address of multiple sensors with PWR_EN line

  This example demonstrates how to chage the i2c address of multiple sensors.

  The library is in BETA, so subscribe to the github repo to recieve updates, or
  just check in periodically:
  https://github.com/PulsedLight3D/LIDARLite_v2_Arduino_Library

  To learn more read over lidarlite.cpp as each function is commented
=========================================================================== */

#include <Wire.h>
#include <LIDARLite.h>


//-----------------LIDARLite-------------------
int sensorPins[] = {2, A3}; // Array of pins connected to the sensor Power Enable lines
int enableSensorPins[] = {2, A3};
unsigned char addresses[] = {0x66,0x68};
//unsigned char address[] = {0x66};
int sensor[] = {A3};
int distance1 = 0;
int distance2 = 0;

LIDARLite myLidarLite;

//-----------------Buzzer-------------------
int sensorBuzzFreq[] = {
  30, 300
};
int sensorBuzzDur[] = {
  500, 100
};
int speakerPin = 9;

//-----------------Setup-------------------
boolean enableOnce = true; //false;


void setup() {
  Serial.begin(115200);
  pinMode(speakerPin, OUTPUT);
  for (int i = 0; i < 2; i++) {
    pinMode(enableSensorPins[i], OUTPUT); // Pin to first LIDAR-Lite Power Enable line
    //digitalWrite(enableSensorPins[i], HIGH);  
}
  digitalWrite(enableSensorPins[0], HIGH); 
  //digitalWrite(enableSensorPins[1], HIGH); 
  
  for (int i = 0; i < 2; i++) {
    beep(speakerPin, sensorBuzzFreq[i], sensorBuzzDur[i]);
    delay(200);
  }
  
  delay(1000);
  myLidarLite.begin();
  myLidarLite.changeAddressMultiPwrEn(2,sensorPins,addresses,false);
  
 
}

void loop() {
   
   if ( millis() > 2000 ) 
   {
      Serial.print("Sensor 0x66: ");
      distance1 = myLidarLite.distance(true,true,0x66);
      Serial.print(myLidarLite.distance(true,true,0x66));
      Serial.print(", Sensor 0x68: ");
      distance2 = myLidarLite.distance(true,true,0x68);
      Serial.print(myLidarLite.distance(true,true,0x68));
      Serial.println();
      checkLIDAR();
  }
}

void checkLIDAR(){
  for(int i=0; i<2; i++){
    if((distance1 < 200)||(distance2 < 200))
    {
       beep(speakerPin,sensorBuzzFreq[i],sensorBuzzDur[i]);
     }  
  }
}
```

**Comment by ak5a** [comment]
Are you currently using the 680uF capacitor? The in-rush into the cap can cause the USB port to shut down, if you unplug and replug the Arduino this often resets the port. A voltage regulator between the sensor and the Arduino (or connecting a 9v battery to an UNO if you're using one of those) should change a lot. 

The initial power draw of the Arduino, Capacitor and LIDAR-Lite when its plugged into the USB port can sometimes make it seem like there's a short to the USB port.

**Comment by mgirlando** [comment]
If you put a more than 20ms delay after begin, it solve the same problem I had.
I fact, if you try to read a value before 20ms, the result is not good.

**Comment by ak5a** [comment]
@mgirlando that's a great note, that delay before reading gives the sensor time to "wake up"
