### ISSUE TITLE
Continuous mode diagram bug

### ISSUE THREAD

**Issue by mainr** [PulsedLight3D/LIDARLite_v2_Arduino_Library#5]
The continuous mode wiring diagram shows a pullup on SDA.
SDA should be wired directly to the MCU, the pullup should be on the MODE pin.
This same error appears throughout much of the Lidar Lite online materials.

**Comment by ak5a** [comment]
Thanks @mainr I see the image you're referring too. I'll get this updated soon.

**Comment by ak5a** [comment]
And fixed! Thank you!
