### ISSUE TITLE
Register definitions don't match Lidar Lite I2C documents

### ISSUE THREAD

**Issue by mainr** [PulsedLight3D/LIDARLite_v2_Arduino_Library#6]
Either I'm looking at OBSOLETE I2C register documents (? quite possible, because there is plenty of contradictory info, even in the same document), or there are some problems with your code.

For instance:
void LIDARLite::beginContinuous(bool modePinLow, char interval, char numberOfReadings,char LidarLiteI2cAddress){
      //  Register 0x45 sets the time between measurements. 0xc8 corresponds to 10Hz
      //  while 0x13 corresponds to 100Hz. Minimum value is 0x02 for proper
      //  operation.
      write(0x45,interval,LidarLiteI2cAddress);
      //  Set register 0x04 to 0x20 to look at "NON-default" value of velocity scale
      //  If you set bit 0 of 0x04 to "1" then the mode pin will be low when done
      if(modePinLow){
        write(0x04,0x21,LidarLiteI2cAddress);
      }else{
        write(0x04,0x20,LidarLiteI2cAddress);
      }
      //  Set the number of readings, 0xfe = 254 readings, 0x01 = 1 reading and
      //  0xff = continuous readings
      write(0x11,numberOfReadings,LidarLiteI2cAddress);
 
you indicate the low bit of register 0x04 controls operation of the MODE pin. Lidar Lite I2C register documents indicate bit 0 of reg 0x04 controls the preamp. Although below this, there is a note concerning "Mode Pin Settings", with values 0 through 3 (meaning it must be at least two bits).

Can you point me to the (most) correct I2C reference?

**Comment by ak5a** [comment]
@mainr here are our current docs: http://lidarlite.com/docs/v2/

... we're in the process of updating all our support sites etc.
